# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'VideoDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VideoDemo

  pod 'SVProgressHUD'
  pod 'OpenCV', '~> 3.0.0'
  pod 'Masonry'

end
